<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EngineVersion Condition="'$(EngineVersion)' == ''">0.1.0</EngineVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="VEngine.Engine" Version="$(EngineVersion)" />
  </ItemGroup>
</Project>
